# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inst.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inst.proto',
  package='ProtoMessage',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ninst.proto\x12\x0cProtoMessage\"P\n\nInstHeader\x12\x0e\n\x06obj_id\x18\x01 \x02(\t\x12\x0e\n\x03ver\x18\x02 \x02(\r:\x01\x30\x12\x11\n\ttick_freq\x18\x03 \x02(\x04\x12\x0f\n\x07has_mem\x18\x04 \x02(\x08\"\xbf\x06\n\x04Inst\x12\n\n\x02pc\x18\x01 \x02(\x04\x12\x0c\n\x04inst\x18\x02 \x01(\x07\x12\x12\n\ninst_bytes\x18\t \x01(\x0c\x12\x0e\n\x06nodeid\x18\x03 \x01(\r\x12\r\n\x05\x63puid\x18\x04 \x01(\r\x12\x0c\n\x04tick\x18\x05 \x01(\x06\x12)\n\x04type\x18\x06 \x01(\x0e\x32\x1b.ProtoMessage.Inst.InstType\x12\x12\n\ninst_flags\x18\x07 \x01(\r\x12\x30\n\nmem_access\x18\x08 \x03(\x0b\x32\x1c.ProtoMessage.Inst.MemAccess\x1a:\n\tMemAccess\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x02(\x04\x12\x0c\n\x04size\x18\x02 \x02(\r\x12\x11\n\tmem_flags\x18\x03 \x01(\r\"\xae\x04\n\x08InstType\x12\x08\n\x04None\x10\x00\x12\n\n\x06IntAlu\x10\x01\x12\n\n\x06IntMul\x10\x02\x12\n\n\x06IntDiv\x10\x03\x12\x0c\n\x08\x46loatAdd\x10\x04\x12\x0c\n\x08\x46loatCmp\x10\x05\x12\x0c\n\x08\x46loatCvt\x10\x06\x12\r\n\tFloatMult\x10\x07\x12\x0c\n\x08\x46loatDiv\x10\x08\x12\r\n\tFloatSqrt\x10\t\x12\x0e\n\nSIMDIntAdd\x10\n\x12\x11\n\rSIMDIntAddAcc\x10\x0b\x12\x0e\n\nSIMDIntAlu\x10\x0c\x12\x0e\n\nSIMDIntCmp\x10\r\x12\x0e\n\nSIMDIntCvt\x10\x0e\x12\x0c\n\x08SIMDMisc\x10\x0f\x12\x0f\n\x0bSIMDIntMult\x10\x10\x12\x12\n\x0eSIMDIntMultAcc\x10\x11\x12\x10\n\x0cSIMDIntShift\x10\x12\x12\x13\n\x0fSIMDIntShiftAcc\x10\x13\x12\x0c\n\x08SIMDSqrt\x10\x14\x12\x10\n\x0cSIMDFloatAdd\x10\x15\x12\x10\n\x0cSIMDFloatAlu\x10\x16\x12\x10\n\x0cSIMDFloatCmp\x10\x17\x12\x10\n\x0cSIMDFloatCvt\x10\x18\x12\x10\n\x0cSIMDFloatDiv\x10\x19\x12\x11\n\rSIMDFloatMisc\x10\x1a\x12\x11\n\rSIMDFloatMult\x10\x1b\x12\x14\n\x10SIMDFloatMultAdd\x10\x1c\x12\x11\n\rSIMDFloatSqrt\x10\x1d\x12\x0b\n\x07MemRead\x10\x1e\x12\x0c\n\x08MemWrite\x10\x1f\x12\r\n\tIprAccess\x10 \x12\x10\n\x0cInstPrefetch\x10!')
)



_INST_INSTTYPE = _descriptor.EnumDescriptor(
  name='InstType',
  full_name='ProtoMessage.Inst.InstType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntAlu', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntMul', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntDiv', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatAdd', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatCmp', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatCvt', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatMult', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatDiv', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatSqrt', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntAdd', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntAddAcc', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntAlu', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntCmp', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntCvt', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDMisc', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntMult', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntMultAcc', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntShift', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDIntShiftAcc', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDSqrt', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatAdd', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatAlu', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatCmp', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatCvt', index=24, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatDiv', index=25, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatMisc', index=26, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatMult', index=27, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatMultAdd', index=28, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMDFloatSqrt', index=29, number=29,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MemRead', index=30, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MemWrite', index=31, number=31,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IprAccess', index=32, number=32,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InstPrefetch', index=33, number=33,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=384,
  serialized_end=942,
)
_sym_db.RegisterEnumDescriptor(_INST_INSTTYPE)


_INSTHEADER = _descriptor.Descriptor(
  name='InstHeader',
  full_name='ProtoMessage.InstHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj_id', full_name='ProtoMessage.InstHeader.obj_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ver', full_name='ProtoMessage.InstHeader.ver', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick_freq', full_name='ProtoMessage.InstHeader.tick_freq', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_mem', full_name='ProtoMessage.InstHeader.has_mem', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=108,
)


_INST_MEMACCESS = _descriptor.Descriptor(
  name='MemAccess',
  full_name='ProtoMessage.Inst.MemAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='ProtoMessage.Inst.MemAccess.addr', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ProtoMessage.Inst.MemAccess.size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_flags', full_name='ProtoMessage.Inst.MemAccess.mem_flags', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=381,
)

_INST = _descriptor.Descriptor(
  name='Inst',
  full_name='ProtoMessage.Inst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pc', full_name='ProtoMessage.Inst.pc', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst', full_name='ProtoMessage.Inst.inst', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_bytes', full_name='ProtoMessage.Inst.inst_bytes', index=2,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='ProtoMessage.Inst.nodeid', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpuid', full_name='ProtoMessage.Inst.cpuid', index=4,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick', full_name='ProtoMessage.Inst.tick', index=5,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ProtoMessage.Inst.type', index=6,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_flags', full_name='ProtoMessage.Inst.inst_flags', index=7,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_access', full_name='ProtoMessage.Inst.mem_access', index=8,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INST_MEMACCESS, ],
  enum_types=[
    _INST_INSTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=942,
)

_INST_MEMACCESS.containing_type = _INST
_INST.fields_by_name['type'].enum_type = _INST_INSTTYPE
_INST.fields_by_name['mem_access'].message_type = _INST_MEMACCESS
_INST_INSTTYPE.containing_type = _INST
DESCRIPTOR.message_types_by_name['InstHeader'] = _INSTHEADER
DESCRIPTOR.message_types_by_name['Inst'] = _INST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstHeader = _reflection.GeneratedProtocolMessageType('InstHeader', (_message.Message,), dict(
  DESCRIPTOR = _INSTHEADER,
  __module__ = 'inst_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.InstHeader)
  ))
_sym_db.RegisterMessage(InstHeader)

Inst = _reflection.GeneratedProtocolMessageType('Inst', (_message.Message,), dict(

  MemAccess = _reflection.GeneratedProtocolMessageType('MemAccess', (_message.Message,), dict(
    DESCRIPTOR = _INST_MEMACCESS,
    __module__ = 'inst_pb2'
    # @@protoc_insertion_point(class_scope:ProtoMessage.Inst.MemAccess)
    ))
  ,
  DESCRIPTOR = _INST,
  __module__ = 'inst_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.Inst)
  ))
_sym_db.RegisterMessage(Inst)
_sym_db.RegisterMessage(Inst.MemAccess)


# @@protoc_insertion_point(module_scope)
